=== hancf6433/TFmall/conf/xsd/ui.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">
    <xs:element name="page" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ui" type="ui" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
        <xs:unique name="ui名不可重复">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="ui">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                 <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
</xs:complexType>
</xs:schema>

=== hancf6433/TFmall/conf/android/creditCard.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：通讯录主页面-->
<page name="creditCard" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="我的应用信用卡">poot(text="信用卡")</ui>
    <ui name="信用卡首页">poot(text="我的二维码")</ui>
    <ui name="我的二维码">poot(text="我的二维码")</ui>
    <ui name="信用卡抢单按钮">poot(text="抢单")</ui>
    <ui name="抢单列表">poot(part_text="目前总计客户")</ui>
    <ui name="抢单列表搜索图标">poot(text="抢单",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="搜索输入框">poot(text="搜索").sibling()[1]</ui>
    <ui name="搜索按钮">poot(text="搜索")</ui>
    <ui name="搜索列表">poot(text="搜索结果:")</ui>
    <ui name="专属客户搜索图标">poot(text="我的客户",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="信用卡我的待办按钮">poot(text="我的待办")</ui>
    <ui name="我的待办列表">poot(text="复核")</ui>
    <ui name="面签按钮">poot(text="面签")</ui>
    <ui name="专属客户列表">poot(text="专属客户")</ui>
    <ui name="非专属客户按钮">poot(text="非专属客户")</ui>
    <ui name="非专属客户列表">poot(text="请输入客户身份证号进行信息搜索")</ui>
    <ui name="身份证输入框">poot(clazz='android.widget.EditText')</ui>
    <ui name="非专属客户搜索按钮">poot(text="搜索")</ui>
    <ui name="未输入身份证搜索提示">poot(text="请检查是否输入18位身份证号码")</ui>
    <ui name="确定按钮">poot(textM="确定.*")</ui>
    <ui name="输入身份证搜索提示">poot(text="未找到该用户申请业务记录")</ui>
    <ui name="补件按钮">poot(text="补件")</ui>
    <ui name="我的补件列表">poot(text="补件客户")</ui>
    <ui name="补件列表搜索图标">poot(text="补件客户",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="搜索的补件客户">poot(text="搜索结果:")</ui>
    <ui name="帮助按钮">poot(text="我的二维码",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="我的帮助列表">poot(text="帮助列表")</ui>
    <ui name="我的客户按钮">poot(text="我的客户")</ui>
    <ui name="申请进度查询按钮">poot(text="申请进度查询")</ui>
    <ui name="进度查询列表搜索图标">poot(text="进度查询列表",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="搜索客户申请进度结果">poot(text="搜索结果")</ui>
    <ui name="客户管理按钮">poot(text="客户管理")</ui>
    <ui name="客户管理列表搜索图标">poot(text="客户管理",clazz='android.view.View').sibling()[-1]</ui>
    <ui name="搜索客户管理列表用户结果">poot(text="test")</ui>
    <ui name="申请进度查询列表">poot(text="进度查询列表")</ui>
    <ui name="客户管理列表">poot(text="成功核发")</ui>
    <ui name="未激活按钮">poot(text="未激活")</ui>
    <ui name="逾期按钮">poot(text="逾期")</ui>
    <ui name="输入少于18位身份证号码提示">poot(text="请检查是否输入18位身份证号码")</ui>
    <ui name="输入非数字提示">poot(text="未找到该用户申请业务记录")</ui>
    <ui name="帮助内容">poot(text="一、信用卡进件环节常见问题")</ui>
    <ui name="帮助详情内容">poot(text="（一）客户办理标准卡的客户类型及需提供的材料")</ui>
    <ui name="成功核发按钮">poot(text="成功核发")</ui>
</page>

=== hancf6433/TFmall/conf/android/myself.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--天府手机银行"我的"页面-->
<page name="myself" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <!--已登录页面-->
    <ui name="我的页面设置按钮">poot(text="设置")</ui>
    <ui name="我的页面退出登录按钮">poot(resource_id="com.ionicframework.cgbank122507:id/btn_login")</ui>
    <ui name="我的页面确定退出按钮">poot(text="确定")</ui>


    <!--未登录-有手机号页面-->
    <ui name="登录页面手机号">poot(textM="1.*")</ui>
    <ui name="登录页面更多登录按钮">poot(text="更多登录")</ui>
    <ui name="登录页面切换账户按钮">poot(text="切换账户")</ui>

    <!--未登录-欢迎回来页面-->
    <ui name="登录页面欢迎回来">poot(text="手机号/熊猫金融账号")</ui>

    <!--账号，密码，协议-->
    <ui name="登录页用户名输入框">poot(resource_id="com.ionicframework.cgbank122507:id/tv_hint_account")</ui>
    <ui name="登录页密码输入框">poot(resource_id="com.ionicframework.cgbank122507:id/tv_hint_pwd")</ui>
    <ui name="登录页同意协议按钮">poot(resource_id="com.ionicframework.cgbank122507:id/cb_agree")</ui>
    <ui name="登录页登录按钮">poot(text="登录")</ui>

    <!--登录成功后提示信息不再提醒-->
    <ui name="登录成功不再提醒按钮">poot(text="不再提醒")</ui>





    <ui name="我的页面我的消息按钮">poot(text="我的消息")</ui>
    <ui name="我的页面我的收藏按钮">poot(text="我的收藏")</ui>
    <ui name="我的页面我上传的文件">poot(text="我上传的文件")</ui>
    <ui name="进入我上传的文件页面">poot(text="我上传的文件")</ui>
    <ui name="我的页面我下载的文件">poot(text="我下载的文件")</ui>
    <ui name="我的页面我的头像">poot(resource_id="com.minxing.client:id/slid_avatar")</ui>
    <ui name="我的个人信息页面">poot(text="个人信息")</ui>
    <ui name="我的页面我的二维码">poot(resource_id="com.minxing.client:id/slid_qr_code")</ui>
    <ui name="二维码加载成功">poot(resource_id="com.minxing.client:id/user_qr_image")</ui>
    <ui name="我的姓名">poot(text="林莹")</ui>
    <ui name="头像">poot(text="头像")</ui>
    <ui name="右上角更多按钮">poot(resource_id="com.minxing.client:id/title_right_more")</ui>
    <ui name="拍照">poot(text="拍照")</ui>
    <ui name="拍照按钮">poot(resource_id="com.huawei.camera:id/shutter_button")</ui>
    <ui name="拍照完成按钮">poot(resource_id="com.huawei.camera:id/done_button")</ui>
    <ui name="保存">poot(text="保存")</ui>
    <ui name="点击设置按钮">poot(resource_id="com.minxing.client:id/slid_setting")</ui>
    <ui name="安全密码">poot(text="安全密码")</ui>
    <ui name="手势解锁">poot(resource_id="com.minxing.client:id/setting_gesture_password_switch")</ui>
    <ui name="最少连接4个点">poot(text="最少连接4个点, 请重新输入")</ui>
    <ui name="请再次绘制解锁图案">poot(text="请再次绘制解锁图案")</ui>
    <ui name="设置手势密码">poot(text="设置手势密码")</ui>
    <ui name="手势验证">poot(text="手势验证")</ui>
    <ui name="手势验证页面">poot(resource_id="com.minxing.client:id/text_phone_number")</ui>
    <ui name="打开天府安逸">poot(resource_id="com.minxing.client:id/mx_open_apk_scene_switch")</ui>
    <ui name="清理缓存">poot(text="清理缓存")</ui>
    <ui name="清理缓存按钮">poot(resource_id="com.minxing.client:id/clean_cache_button")</ui>
    <ui name="确认清空">poot(resource_id="com.minxing.client:id/dialog_ok")</ui>


</page>
