=== hancf6433/TFmall/conf/xsd/ui.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">
    <xs:element name="page" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ui" type="ui" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
        <xs:unique name="ui名不可重复">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="ui">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                 <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
</xs:complexType>
</xs:schema>

=== hancf6433/TFmall/conf/android/mail.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：天府安逸主页面-->
<page name="mail" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="我的应用邮件">poot(text="敏邮")</ui>
    <ui name="添加邮箱">poot(text="添加邮箱")</ui>
    <ui name="邮箱账号输入框">poot(resource_id="com.minxing.client:id/account_email")</ui>
    <ui name="登录">poot(resource_id="com.minxing.client:id/init_btn")</ui>
    <ui name="错误提示框">poot(text="用户名或者密码错误。")</ui>
    <ui name="进入收件箱">poot(resource_id="com.minxing.client:id/btn_mx_mail_message_list_menu")</ui>
    <ui name="成功打开第一封邮件">poot(resource_id="com.minxing.client:id/from")[0]</ui>
    <ui name="邮件列表">poot(resource_id="com.minxing.client:id/from")</ui>
    <ui name="打开邮件有更多按钮">poot(resource_id="com.minxing.client:id/address_simple_more")</ui>
    <ui name="回复">poot(text="回复")</ui>
    <ui name="发送">poot(resource_id="com.minxing.client:id/tv_mx_mail_message_compose_send")</ui>
    <ui name="回复全部">poot(text="回复全部")</ui>
    <ui name="转发">poot(text="转发")</ui>
    <ui name="点击邮件内容">poot(resource_id="com.minxing.client:id/message_content")</ui>
    <ui name="删除">poot(text="删除")</ui>
    <ui name="不要删除">poot(text="不要删除")</ui>
    <ui name="隐藏">poot(text="隐藏")</ui>
    <ui name="收件箱返回按钮">poot(resource_id="com.minxing.client:id/btn_mx_mail_message_list_back")</ui>
    <ui name="更多">poot(text="更多",resource_id="com.minxing.client:id/address_simple_more")</ui>
    <ui name="隐藏">poot(resource_id="com.minxing.client:id/mail_address_hide")</ui>
    <ui name="写邮件">poot(text="写邮件")</ui>
    <ui name="主题">poot(resource_id="com.minxing.client:id/subject")</ui>
    <ui name="邮件内容">poot(resource_id="com.minxing.client:id/message_content")</ui>
    <ui name="断言发件人为空发送邮件失败">poot(resource_id="com.minxing.client:id/tv_mx_mail_message_compose_send")</ui>
    <ui name="断言返回主界面">poot(resource_id="com.minxing.client:id/btn_mx_mail_message_list_menu")</ui>
    <ui name="收件人">poot(resource_id="com.minxing.client:id/contact_btn_container")</ui>
    <ui name="附件">poot(resource_id="com.minxing.client:id/mx_mail_ic_attach")</ui>
    <ui name="任一选择框">poot(resource_id="com.minxing.client:id/media_cbx")</ui>
    <ui name="添加照片">poot(text="添加照片")</ui>
    <ui name="选择确定">poot(resource_id="com.minxing.client:id/media_ok")</ui>
    <ui name="返回按钮">poot(resource_id="com.minxing.client:id/btn_mx_mail_message_compose_back")</ui>
    <ui name="删除草稿">poot(text="删除草稿")</ui>
    <ui name="保存草稿">poot(text="保存草稿")</ui>
    <ui name="编辑">poot(text="编辑")</ui>
    <ui name="点击任一选择框">poot(resource_id="com.minxing.client:id/selected_checkbox")</ui>
    <ui name="断言取消删除成功">poot(resource_id="com.minxing.client:id/selected_checkbox")</ui>
    <ui name="取消全选">poot(text="取消全选")</ui>
    <ui name="全选">poot(text="全选")</ui>
    <ui name="断言出现取消全选">poot(text="取消全选")</ui>
    <ui name="断言出现全选">poot(text="全选")</ui>
    <ui name="搜索">poot(text="搜索")</ui>
    <ui name="搜索邮件成功">poot(resource_id="com.minxing.client:id/subject")</ui>
    <ui name="当前没有数据">poot(resource_id="com.minxing.client:id/nodata")</ui>
    <ui name="进入对应邮件箱">poot(resource_id="com.minxing.client:id/tv_mx_message_list_fragment_title")</ui>
    <ui name="菜单栏">poot(resource_id="com.minxing.client:id/btn_mx_mail_message_list_menu")</ui>
    <ui name="已发送">poot(text="已发送")</ui>
    <ui name="草稿箱">poot(text="草稿箱")</ui>
    <ui name="发件箱">poot(text="发件箱")</ui>
    <ui name="已删除">poot(text="已删除")</ui>
    <ui name="垃圾邮件">poot(text="垃圾邮件")</ui>
    <ui name="设置">poot(text="设置")</ui>
    <ui name="删除账号">poot(text="删除账号")</ui>
    <ui name="取消">poot(text="取消")</ui>
    <ui name="确定">poot(text="确定")</ui>
    <ui name="草稿箱主题">poot(resource_id="com.minxing.client:id/subject_container")</ui>
    <ui name="草稿箱收件人">poot(resource_id="com.minxing.client:id/to_address")</ui>
    <ui name="账号">poot(resource_id="com.minxing.client:id/account_name")</ui>
    <ui name="添加邮箱账号">poot(text="添加邮箱账号")</ui>
    <ui name="输入密码">poot(text="输入密码")</ui>













</page>

=== hancf6433/TFmall/conf/android/attendance.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：通讯录主页面-->
<page name="attendance" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="我的应用智能考勤">poot(text="智能考勤")</ui>
    <ui name="智能考勤首页">poot(text="进入和打卡请选择相同数字")</ui>
    <ui name="智能考勤打卡位置选择取消按钮">poot(textM="Cancel.*")</ui>
    <ui name="考勤记录">poot(textM="考勤记录.*")</ui>
    <ui name="智能考勤打卡图标">poot(text="打卡")</ui>
    <ui name="智能考勤确认打卡图标">poot(textM="确认打卡.*")</ui>
    <ui name="智能考勤取消打卡图标">poot(textM="取消打卡.*")</ui>
    <ui name="考勤记录按钮">poot(textM="考勤记录.*")</ui>
    <ui name="考勤统计">poot(text="考勤统计")</ui>
    <ui name="勤劳小蜜蜂行部日榜">poot(text="勤劳小蜜蜂行部日榜")</ui>
    <ui name="勤劳小蜜蜂个人排行榜">poot(text="勤劳小蜜蜂个人排行榜")</ui>
</page>

=== hancf6433/TFmall/conf/android/work.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：天府安逸主页面-->
<page name="work" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="主页面导航栏第四个按钮工作圈">poot(resource_id="com.minxing.client:id/menu_tab_name",text="工作圈")</ui>
    <ui name="发布按钮">poot(resource_id="com.minxing.client:id/title_right_new_function")</ui>
    <ui name="发布消息">poot(text="发布消息")</ui>
    <ui name="文档输入框">poot(resource_id="com.minxing.client:id/text")</ui>
    <ui name="发送">poot(text="发送")</ui>
    <ui name="回到工作圈页面">poot(resource_id="com.minxing.client:id/title")</ui>
    <ui name="失败停留在当前页面">poot(resource_id="com.minxing.client:id/title_right_button")</ui>
    <ui name="提示">poot(text="提示")</ui>
    <ui name="确定">poot(text="确定")</ui>
    <ui name="删除按钮">poot(resource_id="com.minxing.client:id/mx_id_circel_delete")</ui>
    <ui name="取消">poot(resource_id="com.minxing.client:id/cancel_btn")</ui>
    <ui name="删除">poot(resource_id="com.minxing.client:id/delete_btn")</ui>
    <ui name="拍照按钮">poot(resource_id="com.minxing.client:id/add_camera")</ui>
    <ui name="拍照片">poot(text="拍照片")</ui>
    <ui name="拍照">poot(resource_id="com.huawei.camera:id/shutter_button")</ui>
    <ui name="拍照确定">poot(resource_id="com.huawei.camera:id/done_button")</ui>
    <ui name="图片发送中">poot(resource_id="com.minxing.client:id/cancelBtn")</ui>
    <ui name="第一个更多按钮">poot(resource_id="com.minxing.client:id/comment_btn")[0]</ui>
    <ui name="赞">poot(resource_id="com.minxing.client:id/mx_circle_item_text",text='赞')</ui>
    <ui name="取消赞">poot(resource_id="com.minxing.client:id/mx_circle_item_text",text='取消')</ui>
    <ui name="点赞成功">poot(resource_id="com.minxing.client:id/like_text")</ui>
    <ui name="回复">poot(text="回复")</ui>
    <ui name="测试回复消息">poot(text="测试回复消息")</ui>
    <ui name="分享">poot(text="分享")</ui>
    <ui name="分享到工作圈">poot(text="分享到工作圈")</ui>
    <ui name="分享给同事">poot(text="分享给同事")</ui>
    <ui name="联系人">poot(resource_id="com.minxing.client:id/conversation_avatar")</ui>
    <ui name="创建新聊天">poot(text="创建新聊天")</ui>
    <ui name="公司通讯录">poot(text="公司通讯录")</ui>
    <ui name="选择框">poot(resource_id="com.minxing.client:id/selectIcon")</ui>
    <ui name="确定按钮">poot(com.minxing.client:id/select_finish_btn')[1]</ui>
    <ui name="分享页标题">poot(text='分享',resource_id='com.minxing.client:id/title_name')</ui>
    <ui name="所有">poot(text='所有',resource_id='com.minxing.client:id/title')</ui>
    <ui name="创建工作圈">poot(resource_id="com.minxing.client:id/new_workcircle_btn")</ui>
    <ui name="确定">poot(text="确定")</ui>
    <ui name="不合法的工作圈名称">poot(text="不合法的工作圈名称")</ui>
    <ui name="输入框">poot(text="请输入工作圈名称")</ui>
    <ui name="确定创建">poot(resource_id='com.minxing.client:id/dialog_ok')</ui>
    <ui name="搜索按钮">poot(resource_id='com.minxing.client:id/mx_search_btn')</ui>
    <ui name="选择框">poot(resource_id='com.minxing.client:id/selectIcon')[3]</ui>
    <ui name="确定按钮">poot(resource_id='com.minxing.client:id/select_finish_btn')</ui>
    <ui name="工作圈测试">poot(text="工作圈测试")</ui>
    <ui name="新工作圈当前无数据">poot(resource_id='com.minxing.client:id/nodata')</ui>
    <ui name="成员按钮">poot(resource_id='com.minxing.client:id/member_icon')</ui>
    <ui name="添加成员按钮">poot(resource_id='com.minxing.client:id/person_avatar')[2]</ui>
    <ui name="删除成员按钮">poot(resource_id='com.minxing.client:id/person_avatar')[4]</ui>
    <ui name="删除成员">poot(resource_id='com.minxing.client:id/person_del')[1]</ui>
    <ui name="成员搜索">poot(resource_id='com.minxing.client:id/mx_search_btn')</ui>
    <ui name="成员选择">poot(resource_id='com.minxing.client:id/selectIcon')[0]</ui>
    <ui name="加入工作圈人数3人">poot(text='加入工作圈的用户（3人）')</ui>
    <ui name="加入工作圈人数2人">poot(text='加入工作圈的用户（2人）')</ui>
    <ui name="删除工作圈">poot(text="删除工作圈")</ui>
    <ui name="退出工作圈">poot(text="退出工作圈")</ui>
    <ui name="更多工作圈">poot(text="更多工作圈")</ui>
    <ui name="退出">poot(text="退出")</ui>
    <ui name="创建任务">poot(text="创建任务")</ui>
    <ui name="组织活动">poot(text="组织活动")</ui>
    <ui name="添加">poot(text="添加")</ui>
    <ui name="修改">poot(text="修改")</ui>
    <ui name="完成任务">poot(resource_id='com.minxing.client:id/cell_check')</ui>
    <ui name="有一个任务已完成">poot(text="  有1个任务已完成")</ui>
    <ui name="取消">poot(text="取消")</ui>
    <ui name="添加话题">poot(resource_id='com.minxing.client:id/add_topic')</ui>
    <ui name="添加图片">poot(resource_id='com.minxing.client:id/add_camera')</ui>
    <ui name="话题选项框">poot(resource_id='com.minxing.client:id/imgbtn_checked')[1]</ui>
    <ui name="保存">poot(text="保存")</ui>
    <ui name="新建话题">poot(resource_id='com.minxing.client:id/new_topic')</ui>


</page>

=== hancf6433/TFmall/conf/android/page.xml
<?xml version="1.0" encoding="utf-8" ?>

<page name="page" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="app包名">com.ionicframework.cgbank122507</ui>
    <ui name="等待圈圈">poot(resource_id="android:id/progress")</ui>
    <ui name="等待圈圈2">poot(resource_id="android:id/progress")</ui>
    <ui name="弹窗消息体文本框">poot(resource_id='com.minxing.client:id/main_message')</ui>
    <ui name="弹窗消息取消按钮">poot(resource_id='com.minxing.client:id/dialog_cancel')</ui>
    <ui name="弹窗消息确定按钮">poot(resource_id='com.minxing.client:id/dialog_ok')</ui>
    <ui name="leaks界面">poco("android:id/decor_content_parent")</ui>
    <ui name="app界面">poco(package="com.ionicframework.cgbank122507")</ui>
    <ui name="温馨提示弹窗提示文字文本框">poco(text='确定').parent().sibling()[1]</ui>
    <ui name="温馨提示弹窗确定按钮">poco(text='确定')</ui>
    <ui name="温馨提示弹窗提示文字文本框2">poco(text="温馨提示").sibling()[1]</ui>
    <ui name="没有标题的温馨提示弹窗提示文字文本框">poco(text="重新输入").parent().parent().child("android.view.View")</ui>
    <ui name="有name名的温馨提示信息文本框">poco("com.ionicframework.cgbank122507:id/body")</ui>
    <ui name="弹窗关闭按钮">poco(text="")</ui>
    <ui name="登录按钮">@[text='登录']</ui>
    <ui name="首页按钮">@android.support.v7.app.ActionBar$Tab[0]</ui>
    <ui name="U盾认证页短信验证码输入框">@[text='请输入短信验证码']>..>..>@android.view.View[2]</ui>
    <ui name="手机验证码">poco(textMatches="\d{6}")</ui>
    <ui name="请输入短信验证码文本框">poco(text="请输入短信验证码")</ui>
    <ui name="立即付款按钮">@[text='立即付款']</ui>
    <ui name="支付密码输入框">poco("com.ionicframework.cgbank122507:id/pwd_input")</ui>
    <ui name="请输入密码提示框顶部文本框">poco(textMatches="请输入.*密码")</ui>
    <ui name="确认按钮">poco(text='确认')</ui>
    <ui name="同意按钮">poco(text="同意")</ui>
    <ui name="密码键盘按钮">poco(nameMatches=".+Keyboard___.+",text='${keys}')</ui>
    <ui name="密码键盘删除按钮">poco("CompleteKeyboard___delete")</ui>
    <ui name="密码键盘大小写锁定键按钮">poco("CompleteKeyboard___caps")</ui>
    <ui name="密码键盘数字键盘切换按钮">poco("CompleteKeyboard___num-shift")</ui>
    <ui name="密码键盘字母键盘切换按钮">poco("CompleteKeyboard___sym-shift")</ui>
    <ui name="密码键盘熊猫标志">poco("NumberKeyboard___panda")</ui>
    <ui name="密码键盘空白格">poco(nameMatches=".*board___blank")</ui>
    <ui name="支付银行卡下拉按钮">poco(text="支付账户").sibling("android.view.View")</ui>
    <ui name="选择银行卡">poco(textMatches=".+(${top4CardNumbers})")</ui>
    <ui name="他行卡预留手机号页面">poco(text="请输入手机号")</ui>
    <ui name="下一步按钮">poco(text=" 下一步 ")</ui>
    <ui name="请输入短信验证码框">poco(text="请输入短信验证码")</ui>
    <ui name="天府收银台下一步按钮">poco(text="下一步")</ui>
    <ui name="暂无可用">poco(text="暂无可用")</ui>
    <ui name="优惠券按钮">poco(text="优惠券").parent().child()[1].child()</ui>
    <ui name="可使用的优惠券">poco(text="可使用").parent().parent().child()[2].child().child()</ui>
    <ui name="天府收银台银行卡弹出选择下拉列表框按钮">poco(textMatches="银行卡支付.*").parent().parent().child("android.view.View")[1]</ui>
    <ui name="天府收银台银行卡选择界面选择银行卡">poco(textMatches=".+\(${bottomNumberOfCard}\)")</ui>
    <ui name="添加银行卡">poco(text="添加银行卡")</ui>
    <ui name="请选择银行卡银行卡选择项">poco(text="icon-theme").sibling(textMatches="${bankName}\(${cardNumber}\)")</ui>
</page>

=== hancf6433/TFmall/conf/android/oa.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：通讯录主页面-->
<page name="OA" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="我的应用OA">poot(text="OA插件应用")</ui>
    <ui name="OA首页">poot(resource_id="title",text="OA")</ui>
    <ui name="OA首页协同按钮">poot(text="协同")</ui>
    <ui name="协同页搜索图标">poot(resource_id="more")</ui>
    <ui name="自由协同">poot(text="自由协同")</ui>
    <ui name="关闭按钮">poot(resource_id="closeBtn")</ui>
    <ui name="放弃新建按钮">poot(text="放弃新建")</ui>
    <ui name="新建协同页">poot(text="新建协同")</ui>
    <ui name="协同搜索输入框">poot(clazz="android.widget.EditText")</ui>
    <ui name="暂无数据">poot(text="暂无数据")</ui>
    <ui name="接收人员+号图标">poot(resource_id="edit_receiver")</ui>
    <ui name="联系人ui_test1">poot(text="ui_test1")</ui>
    <ui name="联系人ui_test2">poot(text="ui_test2")</ui>
    <ui name="联系人ui_test3">poot(text="ui_test3")</ui>
    <ui name="确认按钮">poot(text="确认")</ui>
    <ui name="编辑流程替换选项">poot(text="替换")</ui>
    <ui name="编辑流程删除选项">poot(text="删除")</ui>
    <ui name="编辑流程新增选项">poot(text="新增")</ui>
    <ui name="编辑流程修改节点权限">poot(text="修改节点权限")</ui>
    <ui name="审批按钮">poot(text="审批")</ui>
    <ui name="修改节点权限完成按钮">poot(text="完成")</ui>
    <ui name="编辑流程完成按钮">poot(text="完成")</ui>
    <ui name="标题输入框">poot(resource_id="preDiv")</ui>
    <ui name="接收人输入框">poot(resource_id="receiver_container_text")</ui>
    <ui name="再次点击接收人输入框">poot(clazz="android.widget.EditText")</ui>
    <ui name="接收人ui_test1">poot(text="测试")</ui>
    <ui name="接收人ui_test2">poot(text="测试")</ui>
    <ui name="接收人选项框删除图标"></ui>
    <ui name="协同正文输入框">poot(resource_id="content")</ui>
    <ui name="发送按钮">poot(text="发送")</ui>
    <ui name="协同待办按钮">poot(text="待办")</ui>
    <ui name="搜索的协同">poot(text="test")</ui>
    <ui name="取消按钮">poot(text="取消")</ui>
    <ui name="协同已发按钮">poot(text="已发")</ui>
    <ui name="已发送协同">poot(text="test")</ui>
    <ui name="撤销按钮">poot(resource_id="cancelBtn")</ui>
    <ui name="撤销原因输入框">poot(resource_id="content")</ui>
    <ui name="确定按钮">poot(resource_id="sendBtn")</ui>
    <ui name="撤销确定按钮">poot(text="取消").sibling()[-1]</ui>
    <ui name="协同待发按钮">poot(text="待发")</ui>
    <ui name="批量操作按钮">poot(text="刚刚已为你刷新过")</ui>
    <ui name="全选按钮">poot(text="全选")</ui>
    <ui name="删除按钮">poot(text="删除")</ui>
    <ui name="删除确定按钮">poot(text="确定")</ui>
    <ui name="提示框确定按钮">poot(text="确定")</ui>
    <ui name="返回按钮">poot(resource_id="prev")</ui>
    <ui name="表单模板按钮">poot(text="表单模板")</ui>
    <ui name="全部模板按钮">poot(textM=".*全部模板.*")</ui>
    <ui name="行政审批按钮">poot(text="行政审批")</ui>
    <ui name="OA系统业务申请表">poot(text="oa系统业务申请表")</ui>
    <ui name="问题描述输入框">poot(resource_id="field0007",clazz="android.widget.EditText")</ui>
    <ui name="已发送表单协同">poot(part_text="oa系统业务申请表")</ui>
    <ui name="保存到待发按钮">poot(text="保存到待发")</ui>
    <ui name="协同处理按钮">poot(text="处理")</ui>
    <ui name="协同暂存待办按钮">poot(text="暂存待办")</ui>
    <ui name="暂存待办图标">poot(text="1条回复")</ui>
    <ui name="处理意见输入框">poot(resource_id="content")</ui>
    <ui name="协同提交按钮">poot(resource_id="submitBtn")</ui>
    <ui name="协同已办按钮">poot(text="已办")</ui>
    <ui name="已处理协同">poot(text="test")</ui>
    <ui name="归档按钮">poot(text="归档")</ui>
    <ui name="我的文档按钮">poot(text="我的文档")</ui>
    <ui name="归档确定按钮">poot(text="确定")</ui>
    <ui name="归档路径确定按钮">poot(text="确定")</ui>
    <ui name="提示确定按钮">poot(text="确定")</ui>
    <ui name="归档成功提示">poot(text="已成功归档至 “我的文档” 中!")</ui>
    <ui name="删除成功提示">poot(text="删除成功！")</ui>
    <ui name="转发按钮">poot(text="转发")</ui>
    <ui name="转发输入框">poot(text="接收人:").sibling()[1].child()</ui>
    <ui name="接收人删除图标">poot(text="测试").parent().parent().parent().sibling()[0]</ui>
    <ui name="附言输入框">poot(resource_id="content")</ui>
    <ui name="转发协同发送按钮">poot(resource_id="sendBtn")</ui>
    <ui name="转发的协同">poot(text="test(由ui_test1原发)")</ui>
    <ui name="批处理按钮">poot(text="批处理")</ui>
    <ui name="批处理确定按钮">poot(resource_id="submitBtn")</ui>
    <ui name="已发送第二个协同">poot(text="test2")</ui>
    <ui name="取回按钮">poot(resource_id="takeBackBtn")</ui>
    <ui name="重新处理按钮">poot(text="否，重新处理")</ui>
    <ui name="知道了提示语">poot(text="知道了")</ui>
    <ui name="流程按钮">poot(resource_id="workflowBtn")</ui>
    <ui name="催办按钮">poot(text="唐红霞").sibling()[12]</ui>
    <ui name="催办理由输入框">poot(resource_id="content")</ui>
    <ui name="催办成功提示">poot(text="催办成功！")</ui>
    <ui name="催办成功提示框确定按钮">poot(text="确定")</ui>
    <ui name="流程返回按钮">poot(resource_id="goBackBtn")</ui>
    <ui name="协同详情页返回按钮">poot(textM=".*返回.*")</ui>
    <ui name="编辑按钮">poot(resource_id="editBtn")</ui>
    <ui name="新闻按钮">poot(text="新闻")</ui>
    <ui name="搜索按钮">poot(text="搜索")</ui>
    <ui name="新闻搜索输入框">poot(text="取消").parent().sibling()[1]</ui>
    <ui name="搜索的新闻">poot(resource_id="news_list_title",text="UI自动化测试")</ui>
    <ui name="要查看的新闻">poot(resource_id="news_list_title",text="UI自动化测试")</ui>
    <ui name="新闻正文内容">poot(text="UI自动化测试")</ui>
    <ui name="阅读全文按钮">poot(resource_id="news_list_a")[0]</ui>
    <ui name="评论图标">poot(resource_id="comment").child()[0]</ui>
    <ui name="评论输入框">poot(resource_id="reply_content")</ui>
    <ui name="评论内容">poot(text="test")</ui>
    <ui name="删除图标">poot(text="test").sibling()[3]</ui>
    <ui name="收藏按钮">poot(text="收藏")</ui>
    <ui name="取消收藏按钮">poot(text="取消收藏")</ui>
    <ui name="公文按钮">poot(text="公文")</ui>
    <ui name="搜索图标">poot(resource_id="title").sibling()[1]</ui>
    <ui name="公文搜索输入框">poot(text="取消").parent().sibling()[1]</ui>
    <ui name="搜索的公文">poot(textM=".*test")</ui>
    <ui name="要回退的公文">poot(text=" 测试回退待办公文")</ui>
    <ui name="菜单栏">poot(text="edocSummary")</ui>
    <ui name="回退按钮">poot(textM="回退.*")</ui>
    <ui name="回退原因输入框">poot(resource_id="edoc_deal_content")</ui>
    <ui name="确定图标">poot(text="确定")</ui>
    <ui name="升级按钮">poot(part_text="升级")</ui>
    <ui name="撤销的公文">poot(textM=".*测试撤销待办公文")</ui>
    <ui name="公文处理按钮">poot(resource_id="deal")</ui>
    <ui name="菜单栏按钮">poot(resource_id="deal").sibling()[0]</ui>
    <ui name="公文撤销按钮">poot(text="撤销")</ui>
    <ui name="公文撤销原因输入框">poot(resource_id="edoc_deal_content")</ui>
    <ui name="公文确定按钮">poot(text="确定")</ui>
    <ui name="处理的公文">poot(textM=".*test")</ui>
    <ui name="暂存待办按钮">poot(text="暂存待办")</ui>
    <ui name="暂存图标">poot(text="暂存")</ui>
    <ui name="提交按钮">poot(text="提交")</ui>
    <ui name="发文选项">poot(text="发文")</ui>
    <ui name="已办按钮">poot(text="已办")</ui>
    <ui name="全部待办按钮">poot(resource_id="allPendingTab")</ui>
    <ui name="取回确认按钮">poot(text="取消").sibling()[-1]</ui>
    <ui name="公文取回按钮">poot(resource_id="takeBack")</ui>
    <ui name="要加签的公文">poot(textM=".*测试加签审批人员")</ui>
    <ui name="公文菜单栏">poot(resource_id="goBack").sibling()[1]</ui>
    <ui name="加签按钮">poot(text="加签")</ui>
    <ui name="公文确认按钮">poot(resource_id="submit")</ui>
    <ui name="加签的人员">poot(text="ui_test2")</ui>
    <ui name="完成按钮">poot(text="完成")</ui>
    <ui name="终止的公文">poot(textM=".*测试终止待办公文")</ui>
    <ui name="终止按钮">poot(textM="终止.*")</ui>
    <ui name="终止输入框">poot(resource_id="edoc_deal_content")</ui>
    <ui name="处理的收文">poot(textM=".*测试收文")</ui>
    <ui name="收文按钮">poot(text="收文")</ui>
    <ui name="公告按钮">poot(part_text="公告")</ui>
    <ui name="公告搜索图标">poot(resource_id="search")</ui>
    <ui name="搜索输入框">poot(text="取消").parent().sibling()[1]</ui>
    <ui name="搜索的公告">poot(text="UI自动化测试")</ui>
    <ui name="查看的公告">poot(text="UI自动化测试")</ui>
    <ui name="发起表单">poot(text="发起表单")</ui>
    <ui name="表单搜索图标">poot(resource_id="more")</ui>
    <ui name="搜索框">poot(resource_id="subject")</ui>
    <ui name="搜索的表单">poot(text="工作沟通")</ui>
    <ui name="发送的表单模板">poot(part_text="oa系统业务申请表")</ui>
    <ui name="协同菜单栏">poot(resource_id="switch_pop_btn")</ui>
    <ui name="协同确定按钮">poot(text="确定")</ui>
    <ui name="指定回退按钮">poot(textM="指定回退.*")</ui>
    <ui name="流程重走按钮">poot(text="流程重走")</ui>
    <ui name="移交按钮">poot(textM="移交.*")</ui>
    <ui name="确认">poco("select_okBtn")</ui>
    <ui name="正文">poot(text="正文")</ui>
    <ui name="公文正文内容">poot(text="此为正文内容")</ui>
    <ui name="知会按钮">poot(text="知会")</ui>
    <ui name="知会节点">poot(text="[知会]")</ui>
</page>

=== hancf6433/TFmall/conf/android/vconference.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：天府安逸主页面-->
<page name="vconference" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="我的应用视频会议">poot(text="视频会议")</ui>
    <ui name="视频会议首页">poot(text="加入视频会议")</ui>
    <ui name="请输入视频会议号输入框">poot(clazz='android.widget.EditText')</ui>
    <ui name="呼叫">poot(resource_id="com.cisco.jabber.guest:id/jgsdk_call_button")</ui>
    <ui name="摄像头转换按钮">poot(resource_id="com.cisco.jabber.guest:id/jgsdk_switch_camera")</ui>
    <ui name="证书无效">poot(text="证书无效")</ui>
    <ui name="接受">poot(text="接受")</ui>
    <ui name="点击主界面">poot(resource_id="com.cisco.jabber.guest: id / jgsdk_texture")</ui>
    <ui name="视频">poot(text="视频",clazz="android.widget.Button")</ui>
    <ui name="挂断按钮">poot(clazz="android.widget.ImageView")</ui>
    <ui name="视频已停止">poot(text="视频已停止")</ui>
    <ui name="加入视频会议">poot(text="加入视频会议")</ui>
</page>

=== hancf6433/TFmall/conf/android/contact.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--其他页面：通讯录主页面-->
<page name="contact" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">
    <ui name="通讯录页搜索图标">poot(resource_id="com.minxing.client:id/title_right_search_function")</ui>
    <ui name="通讯录页搜索输入框">poot(text="姓名/拼音/部门名")</ui>
    <ui name="通讯录搜索的联系人">poot(resource_id="com.minxing.client:id/name",text="ui_test2")</ui>
    <ui name="通讯录搜索的部门">poot(resource_id="com.minxing.client:id/name",text="科技研发部")</ui>
    <ui name="通讯录页+号图标">poot(resource_id="com.minxing.client:id/title_right_new_function")</ui>
    <ui name="通讯录添加联系人页">poot(text="按姓名查找")</ui>
    <ui name="加为联系人按钮">poot(text=" 加为联系人")</ui>
    <ui name="通讯录添加的联系人">poot(resource_id="com.minxing.client:id/name",text="ui_test2")</ui>
    <ui name="添加联系人页公司通讯录按钮">poot(text="公司通讯录")</ui>
    <ui name="已添加的联系人">poot(resource_id="com.minxing.client:id/name",text="ui_test3")</ui>
    <ui name="删除联系人按钮">poot(text=" 删除联系人")</ui>
    <ui name="删除联系人确定按钮">poot(text="确定")</ui>
    <ui name="公司通讯录添加的联系人">poot(resource_id="com.minxing.client:id/name",text="ui_test3")</ui>
    <ui name="通讯录页群聊按钮">poot(text="群聊")</ui>
    <ui name="删除群聊确认按钮">poot(resource_id="com.minxing.client:id/dialog_ok")</ui>
    <ui name="通讯录页公众号按钮">poot(text="公众号")</ui>
    <ui name="通讯录页特别关注按钮">poot(text="特别关注")</ui>
    <ui name="通讯录页公司通讯录按钮">poot(text="公司通讯录")</ui>
    <ui name="已保存群聊">poot(text="testSaveToContact")</ui>
    <ui name="联系人信息页特别关注按钮">poot(resource_id="com.minxing.client:id/mx_swith_attention")</ui>
    <ui name="设置的特别关注">poot(resource_id="com.minxing.client:id/name",text="ui_test2")</ui>
    <ui name="特别关注删除确定按钮">poot(resource_id="com.minxing.client:id/dialog_ok")</ui>
    <ui name="联系人信息页取消特别关注按钮">poot(resource_id="com.minxing.client:id/mx_swith_attention")</ui>
    <ui name="联系人手机号">poot(text="13612345678")</ui>
    <ui name="发送短信按钮">poot(resource_id="com.minxing.client:id/sms_btn")</ui>
    <ui name="发送短信页">poot(text="短信/彩信")</ui>
    <ui name="公司通讯录页关闭按钮">poot(resource_id="com.minxing.client:id/title_to_root")</ui>
    <ui name="保存至手机按钮">poot(resource_id="com.minxing.client:id/add_to_mobile_btn")</ui>
    <ui name="保存结果"></ui>
    <ui name="拨打电话按钮">poot(resource_id="com.minxing.client:id/call_btn")</ui>
    <ui name="电话页">poot(resource_id="com.android.contacts:id/dialButton")</ui>
    <ui name="联系人信息页工作圈按钮">poot(text="工作圈")</ui>
    <ui name="联系人工作圈页">poot(resource_id="com.minxing.client:id/title_name",text="工作圈")</ui>
    <ui name="联系人信息页文件按钮">poot(text="文件")</ui>
    <ui name="联系人文件页">poot(resource_id="com.minxing.client:id/title_name",text="文件")</ui>
    <ui name="搜索的联系人">poot(resource_id="com.minxing.client:id/name",text="丁涛")</ui>
    <ui name="当前没有数据">poot(resource_id="com.minxing.client:id/nodata")</ui>
    <ui name="当前没有结果">poot(textM="当前没有结.*")</ui>
    <ui name="按姓名查找页清除按钮">poot(resource_id="com.minxing.client:id/remove_icon")</ui>
    <ui name="清除的内容">poot(resource_id="com.minxing.client:id/searchName",text="ui_test2")</ui>
    <ui name="通讯录联系人ui_test1">poot(resource_id="com.minxing.client:id/name",text="ui_test1")</ui>
</page>

=== hancf6433/TFmall/conf/android/mall.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--天府手机银行"我的"页面-->
<page name="mall" xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn ../xsd/ui.xsd">

    <!--商城-->
    <ui name="手机银行首页定位按钮">poot(resource_id="com.ionicframework.cgbank122507:id/tv_choose_city")</ui>
    <ui name="手机银行主导航界面我的按钮">poot(resource_id="com.ionicframework.cgbank122507:id/tab_lable",text="我的")</ui>
    <ui name="手机银行主导航界面商城按钮">poot(resource_id="com.ionicframework.cgbank122507:id/tab_lable",text="商城")</ui>
    <ui name="商城首页类目按钮">poot(resource_id="com.ionicframework.cgbank122507:id/btn_mall_more")</ui>
    <ui name="商城首页购物车按钮">poot(resource_id="com.ionicframework.cgbank122507:id/btn_mall_cart")</ui>
    <ui name="商城首页搜索框">poot(text="搜索商品、商家")</ui>
    <ui name="搜索有结果">poot(text="￥")</ui>
    <ui name="搜索结果页面排序框">poot(text="综合")</ui>
    <ui name="搜索页面搜索框">poot(text="搜索商品名称")</ui>
    <ui name="搜索页面商城按钮">poot(text="商城")</ui>
    <ui name="搜索页面店铺按钮">poot(text="店铺")</ui>
    <ui name="搜索商品成功商品列表综合按钮">poot(text="综合")</ui>
    <ui name="商品列表页第一个商品">poot(className="android.widget.ListView").child[1]</ui>
    <ui name="商品详情页立即购买按钮">poot(text="立即购买")</ui>
    <ui name="商平详情页加入购物车按钮">poot(text="加入购物车")</ui>
    <ui name="手机银行首页退出按钮">poot(resource_id="com.ionicframework.cgbank122507:id/iv_logout")</ui>
    <ui name="商城首页分类按钮">poot(resource_id="com.ionicframework.cgbank122507:id/btn_mall_more")</ui>
    <ui name="酒水饮料">poot(text="酒水饮料")</ui>
    <ui name="葡萄酒">poot(text='葡萄酒')</ui>
    <!--<></ui>-->
</page>
